#!/bin/bash

export TERM=linux

ensemble-log "Database relation changed"

set -x
echo $ENSEMBLE_REMOTE_UNIT modified its settings
echo Relation settings:
relation-get --format json
echo Relation members:
relation-list
true
