#!/bin/bash

set -eu # -x for verbose logging to ensemble debug-log

ensemble-log "Installing ruby, apache, passenger"
apt-get -y install -qq ruby ruby-dev rake libapache2-mod-passenger
apt-get -y install -qq libsqlite3-dev libsqlite3-ruby

install_root=`config-get install_root`
app_name=`config-get app_name`
app_dir="$install_root/$app_name"
repo_url=`config-get repo_url`
repo_branch=`config-get repo_branch`
repo_type=`config-get repo_type`
pull_git_app() {
  apt-get -y install -qq git-core
  umask 022
  git clone $repo_url -b $repo_branch $app_dir
}
pull_bzr_app() {
  apt-get -y install -qq git-core
  umask 022
  bzr branch $repo_url -b $repo_branch $app_dir
}
install_app() {
  ensemble-log "Installing your rails app into $app_dir"
  pull_git_app
  chown -Rf ubuntu.ubuntu $app_dir
}
[ -d $app_dir ] || install_app

install_bundle() {
  REALLY_GEM_UPDATE_SYSTEM=true gem update --system
  gem install 'bundler' --no-ri --no-rdoc
  cd $app_dir && bundle install
}
install_bundle

vhost_file="/etc/apache2/conf.d/rails.conf"
configure_passenger() {
  ensemble-log "Writing apache/passenger config: $vhost_file"
  cat > $vhost_file <<-EOS
  <VirtualHost *:80>
      ServerSignature Off
      DocumentRoot $app_dir/public
      <Directory $app_dir/public>
          AllowOverride all
          Options -MultiViews
      </Directory>
      LogLevel warn
      ErrorLog /var/log/apache2/$app_name-error.log
      CustomLog /var/log/apache2/$app_name-access.log combined
  </VirtualHost>
  EOS
}
[ -f $vhost_file ] || configure_passenger

